language: node_js
node_js:
  - 8

sudo: required

services:
    - docker

before_install:
    - docker build -t melsheikh91/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true melsheikh91/docker-react npm run test -- --coverage
deploy:
    edge: true
    provider: elasticbeanstak
    region: us-east-2
    app: react_-sample
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-333547288842"
    bucket_path: "react_-sample" 
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

